# POLITICAL NEWS BIAS DETECTOR

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load Data

In [ ]:
filename = "allsides_balanced_news_headlines-texts.csv"

import requests
url = 'https://raw.githubusercontent.com/irgroup/Qbias/refs/heads/main/allsides_balanced_news_headlines-texts.csv'
res = requests.get(url, allow_redirects=True)
with open(filename,'wb') as file:
    file.write(res.content)

df = pd.read_csv(filename)
print("Shape:", df.shape)
print(df.head(10))
print(f"Columns: {df.columns}")

Shape: (21754, 7)
   Unnamed: 0                                              title  \
0           0           Gun Violence Over Fourth of July Weekend   
1           1           Gun Violence Over Fourth of July Weekend   
2           2           Gun Violence Over Fourth of July Weekend   
3           3  Yellen Warns Congress of 'Economic Recession' ...   
4           4  Yellen Warns Congress of 'Economic Recession' ...   
5           5  Yellen Warns Congress of 'Economic Recession' ...   
6           6                       Night 2: Christie on Hillary   
7           7                       Night 2: Christie on Hillary   
8           8                       Night 2: Christie on Hillary   
9           9  Denying Abortion Medication Could Violate Civi...   

                                                tags  \
0  ['Protests', 'Fourth Of July', 'Gun Control An...   
1  ['Protests', 'Fourth Of July', 'Gun Control An...   
2  ['Protests', 'Fourth Of July', 'Gun Control An...   
3  ['Jane

Drop 'Unnamed: 0' column and reset index

In [ ]:
df.drop(columns= ["Unnamed: 0"], inplace = True)
df.reset_index(drop = True, inplace = True)
print(df.columns)

Index(['title', 'tags', 'heading', 'source', 'text', 'bias_rating'], dtype='object')


In [ ]:
print(df.head())

                                               title  \
0           Gun Violence Over Fourth of July Weekend   
1           Gun Violence Over Fourth of July Weekend   
2           Gun Violence Over Fourth of July Weekend   
3  Yellen Warns Congress of 'Economic Recession' ...   
4  Yellen Warns Congress of 'Economic Recession' ...   

                                                tags  \
0  ['Protests', 'Fourth Of July', 'Gun Control An...   
1  ['Protests', 'Fourth Of July', 'Gun Control An...   
2  ['Protests', 'Fourth Of July', 'Gun Control An...   
3  ['Janet Yellen', 'Debt Ceiling', 'Economic Pol...   
4  ['Janet Yellen', 'Debt Ceiling', 'Economic Pol...   

                                             heading                 source  \
0  Chicago Gun Violence Spikes and Increasingly F...  New York Times (News)   
1  ‘Bullets just came from nowhere’: Fourth of Ju...        Chicago Tribune   
2  Dozens of shootings across US mark bloody July...   New York Post (News)   
3  Federal

### Data Exploration

In [ ]:
# Explore number of labeled articles in each bucket
left_df = df[df["bias_rating"] == "left"]
right_df = df[df["bias_rating"] == "right"]
center_df = df[df["bias_rating"] == "center"]

print(f"Left: {left_df.shape}")
print(f"Right: {right_df.shape}")
print(f"Center: {center_df.shape}")

Left: (10275, 6)
Right: (7226, 6)
Center: (4253, 6)


In [ ]:
# Explore word counts across articles
left_word_count = sum(left_df["text"].fillna("").str.split().apply(len))
right_word_count = sum(right_df["text"].fillna("").str.split().apply(len))
center_word_count = sum(center_df["text"].fillna("").str.split().apply(len))

print("Left Leaning Articles Word Count:", left_word_count)
print("Right Leaning Articles Word Count:", right_word_count)
print("Center Leaning Articles Word Count:", center_word_count)

Left Leaning Articles Word Count: 658761
Right Leaning Articles Word Count: 481681
Center Leaning Articles Word Count: 301266


There is a discrepancy in the total word count of the articles labeled left, right, and center

In [ ]:
# Analyze the average lengths of left, right, and center leaning articles to check quality of dataset
average_length_left = left_word_count / left_df.shape[0]
average_length_right = right_word_count / right_df.shape[0]
average_length_center = center_word_count / center_df.shape[0]

print("Average length of left-leaning articles:", average_length_left)
print("Average length of right-leaning articles:", average_length_right)
print("Average length of center-leaning articles:", average_length_center)

Average length of left-leaning articles: 64.11299270072993
Average length of right-leaning articles: 66.65942430113479
Average length of center-leaning articles: 70.83611568304725


In [ ]:
# Explore tag lengths across articles
left_tags_count = sum(left_df["tags"].fillna("").str.split(",").apply(len))
right_tags_count = sum(right_df["tags"].fillna("").str.split(",").apply(len))
center_tags_count = sum(center_df["tags"].fillna("").str.split(",").apply(len))

print("Left Leaning Articles Tags Count:", left_tags_count)
print("Right Leaning Articles Tags Count:", right_tags_count)
print("Center Leaning Articles Tags Count:", center_tags_count)

Left Leaning Articles Tags Count: 35898
Right Leaning Articles Tags Count: 27676
Center Leaning Articles Tags Count: 19801


Tags counts are closer

### Data Preparation

In [ ]:
# Convert words to lowercase in all columns
df = df.map(lambda x: x.lower() if isinstance(x, str) else x)
print(df.head())

                                               title  \
0           gun violence over fourth of july weekend   
1           gun violence over fourth of july weekend   
2           gun violence over fourth of july weekend   
3  yellen warns congress of 'economic recession' ...   
4  yellen warns congress of 'economic recession' ...   

                                                tags  \
0  ['protests', 'fourth of july', 'gun control an...   
1  ['protests', 'fourth of july', 'gun control an...   
2  ['protests', 'fourth of july', 'gun control an...   
3  ['janet yellen', 'debt ceiling', 'economic pol...   
4  ['janet yellen', 'debt ceiling', 'economic pol...   

                                             heading                 source  \
0  chicago gun violence spikes and increasingly f...  new york times (news)   
1  ‘bullets just came from nowhere’: fourth of ju...        chicago tribune   
2  dozens of shootings across us mark bloody july...   new york post (news)   
3  federal

Create an X and Y training and testing set for Milestone 1

In [ ]:
X = df[['title', 'heading', 'text','source','tags']]
y = df["bias_rating"]
print(X.head())
print(y.head())

                                               title  \
0           gun violence over fourth of july weekend   
1           gun violence over fourth of july weekend   
2           gun violence over fourth of july weekend   
3  yellen warns congress of 'economic recession' ...   
4  yellen warns congress of 'economic recession' ...   

                                             heading  \
0  chicago gun violence spikes and increasingly f...   
1  ‘bullets just came from nowhere’: fourth of ju...   
2  dozens of shootings across us mark bloody july...   
3  federal government will run out of cash on oct...   
4  yellen tells congress that u.s. will run out o...   

                                                text                 source  \
0  as yasmin miller drove home from a laundromat ...  new york times (news)   
1  as many chicagoans were celebrating the fourth...        chicago tribune   
2  the nation’s 4th of july weekend was marred by...   new york post (news)   
3  treasur

In [ ]:
label_mapping = {'left': 0, 'center': 1, 'right': 2}

y_mapped = y.map(label_mapping)
y_array = np.array((y_mapped).values.tolist())
print(y_array[:5])

# Combine columns for training
X_text = np.array((X["title"].fillna("") + ". " + X["heading"].fillna("") + ". " + X["source"].fillna("") + ". " + X["tags"].fillna("") + ". " + X["text"].fillna("")).to_list())

print(X_text[:5])
print(type(X_text[0]))

[0 1 2 2 0]
["gun violence over fourth of july weekend. chicago gun violence spikes and increasingly finds the youngest victims. new york times (news). ['protests', 'fourth of july', 'gun control and gun rights', 'chicago', 'violence in america']. as yasmin miller drove home from a laundromat in chicago’s englewood neighborhood last weekend, a gunman in another car peppered her red hyundai sedan with bullets, grazing her head and striking her son, sincere gaston, in the chest. sincere died in his car seat. he was 20 months old.\non june 20, a man fired gunshots through the back of a dark blue suv, wounding the 27-year-old man driving and hitting his stepson, mekhi james, in the back, killing him. mekhi was three.\ntwo girls, both aged three, were hospitalized..."
 "gun violence over fourth of july weekend. ‘bullets just came from nowhere’: fourth of july weekend gun violence kills at least 17, including 7-year-old-girl. chicago tribune. ['protests', 'fourth of july', 'gun control and g

In [ ]:
# Split into training, testing with even ratio between articles from each side (stratify)
from sklearn.model_selection import train_test_split
X_train, X_tmp, y_train, y_tmp = train_test_split(X_text, y_mapped, test_size=0.3, stratify=y_mapped, random_state=42, shuffle= True)
X_test, X_valid, y_test, y_valid = train_test_split(X_tmp, y_tmp, test_size=0.5, stratify=y_tmp, random_state=42, shuffle= True)
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")
print(f"X_valid shape: {X_valid.shape}")
print(f"y_valid shape: {y_valid.shape}")

print(X_train[:5])
print(y_train[:5])

X_train shape: (15227,)
y_train shape: (15227,)
X_test shape: (3263,)
y_test shape: (3263,)
X_valid shape: (3264,)
y_valid shape: (3264,)
["perspectives: the doj's dismissal of michael flynn's case. if michael flynn did nothing wrong, why didn’t he tell the truth?. david ignatius. ['michael flynn', 'criminal justice', 'justice department', 'justice', 'russia', 'russia investigation', 'white house', 'fbi', 'defense and security']. with the justice department’s move thursday to drop its case against former national security adviser michael flynn, it’s useful to go back to a basic question: if flynn did nothing wrong when he called the russian ambassador on dec. 29, 2016, the day president barack obama imposed sanctions on russia for interfering in the presidential election, why did he conceal it?\none issue from the beginning was whether flynn’s call to ambassador sergey kislyak violated the logan act, which bars private u.s. citizens from trying to influence another country about..."
 "

In [ ]:
from sklearn.model_selection import train_test_split
import keras_hub
import tensorflow as tf
from tensorflow import keras
import numpy as np
from collections import Counter
import huggingface_hub
from transformers import AutoTokenizer, TFBertModel
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
# setup tokenizer
model_name = "bert-base-uncased" #  "meta-llama/Llama-2-7b-chat-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
def tokenize_all(numpy_object):
  tokenized_texts = []
  for text in numpy_object.tolist():
    # tokenized = tokenizer(text, return_tensors="np") # for oLlama
    # tokenized_texts.append(tokenized.input_ids[0])
    tokenized = tokenizer(text, padding=True, truncation=True, return_tensors="np")
    tokenized_texts.append(tokenized.input_ids[0])

  max_length = 250
  padded_sequences = pad_sequences(tokenized_texts, maxlen=max_length, padding='post', truncating='post')
  return padded_sequences

X_train_tokenized = tokenize_all(X_train)
X_test_tokenized = tokenize_all(X_test)
X_valid_tokenized = tokenize_all(X_valid)

print(f"X_train shape: {X_train_tokenized.shape}")
print(f"X_test shape: {X_test_tokenized.shape}")
print(f"X_valid shape: {X_valid_tokenized.shape}")

print(X_train_tokenized[:5])
print(X_test_tokenized[:5])
print(X_valid_tokenized[:5])

X_train shape: (15227, 250)
X_test shape: (3263, 250)
X_valid shape: (3264, 250)
[[  101 15251  1024 ...     0     0     0]
 [  101  2343  8398 ...     0     0     0]
 [  101  8398  6985 ...     0     0     0]
 [  101  4455  2005 ...     0     0     0]
 [  101  5924 19164 ...     0     0     0]]
[[  101 17688  2099 ...     0     0     0]
 [  101  2280  8398 ...     0     0     0]
 [  101 11417 15493 ...     0     0     0]
 [  101  2054  2000 ...     0     0     0]
 [  101 15251  1024 ...     0     0     0]]
[[  101 15941 12055 ...     0     0     0]
 [  101 23944 24641 ...     0     0     0]
 [  101  2715  2050 ...     0     0     0]
 [  101  2047 23702 ...     0     0     0]
 [  101 15251  1024 ...     0     0     0]]




### Building Baseline Model: Custom LSTM



Our baseline model will be a simple custom-built LSTM

In [ ]:
# Create the train and validation dataset
BATCH = 32
train_ds = (
    tf.data.Dataset.from_tensor_slices((X_train_tokenized, y_train))
      .shuffle(10_000)
      .batch(BATCH)
      .prefetch(tf.data.AUTOTUNE)
)

val_ds = (
    tf.data.Dataset.from_tensor_slices((X_valid_tokenized, y_valid))
      .batch(BATCH)
      .prefetch(tf.data.AUTOTUNE)
)

In [ ]:
from keras.regularizers import l2
# Build our bidirectional LSTM model (embedding -> dropout -> biD -> dropout -> Dense -> Dense)
vocab_size = tokenizer.vocab_size
num_classes = 3

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=128))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Bidirectional(LSTM(64, return_sequences=False, kernel_regularizer=l2(0.001))))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(32, activation='relu', kernel_regularizer=l2(0.001)))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
es = tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=[es],
    verbose="auto",
)

Epoch 1/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 19s 24ms/step - accuracy: 0.5251 - loss: 1.0780 - val_accuracy: 0.9066 - val_loss: 0.3724
Epoch 2/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.9187 - loss: 0.3465 - val_accuracy: 0.9482 - val_loss: 0.2524
Epoch 3/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 21s 23ms/step - accuracy: 0.9551 - loss: 0.2193 - val_accuracy: 0.9602 - val_loss: 0.1864
Epoch 4/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 12s 24ms/step - accuracy: 0.9671 - loss: 0.1638 - val_accuracy: 0.9602 - val_loss: 0.1953
Epoch 5/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - accuracy: 0.9703 - loss: 0.1458 - val_accuracy: 0.6547 - val_loss: 0.8055
Epoch 6/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 19s 25ms/step - accuracy: 0.9004 - loss: 0.3165 - val_accuracy: 0.9835 - val_loss: 0.1350
Epoch 7/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.9919 - loss: 0.0871 - val_accuracy: 0.9850 - val_loss: 0.1074
Epoch 8/20
476/476 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.9976 - loss: 0.0497 - 

Evaluate the baseline model

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Get predictions and evaluate our baseline custom LSTM
pred_probs = model.predict(X_test_tokenized, batch_size=32)
y_pred = np.argmax(pred_probs, axis=1)

left_counter = 0
right_counter = 0
center_counter = 0
for i in range(len(y_pred)):
  if y_pred[i] == 0:
    left_counter += 1
  elif y_pred[i] == 1:
    center_counter += 1
  else:
    right_counter += 1

# conf_matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
conf_matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
print(f"Left: {left_counter}")
print(f"Right: {right_counter}")
print(f"Center: {center_counter}")
print(conf_matrix)

y_true = y_test

print(classification_report(y_true, y_pred,
                            target_names=['left', 'center', 'right']))
                            # target_names=['left','right']))

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
Left: 1534
Right: 1090
Center: 639
[[1529    3    9]
 [   3  629    6]
 [   2    7 1075]]
              precision    recall  f1-score   support

        left       1.00      0.99      0.99      1541
      center       0.98      0.99      0.99       638
       right       0.99      0.99      0.99      1084

    accuracy                           0.99      3263
   macro avg       0.99      0.99      0.99      3263
weighted avg       0.99      0.99      0.99      3263



Above are our results from our initial test using an LSTM. These results are very impressive and suggest that our baseline model performs exceptionally well.

### Term Frequency with Logistic Regression Model

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Create a pipeline with TF-IDF and Logistic Regression
model = make_pipeline(
    TfidfVectorizer(max_features=5000, ngram_range=(1, 2), stop_words='english'),
    LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, random_state=42)
)

# Fit model
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)
y_pred = np.argmax(pred_probs, axis=1)

# Evaluate model
left_counter = 0
right_counter = 0
center_counter = 0
for i in range(len(y_pred)):
  if y_pred[i] == 0:
    left_counter += 1
  elif y_pred[i] == 1:
    center_counter += 1
  else:
    right_counter += 1

conf_matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
print(f"Left: {left_counter}")
print(f"Right: {right_counter}")
print(f"Center: {center_counter}\n")
print(conf_matrix)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Left: 1534
Right: 1090
Center: 639

[[1529    3    9]
 [   3  629    6]
 [   2    7 1075]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1541
           1       0.98      0.99      0.99       638
           2       0.99      0.99      0.99      1084

    accuracy                           0.99      3263
   macro avg       0.99      0.99      0.99      3263
weighted avg       0.99      0.99      0.99      3263


Accuracy: 0.9908


The term frequency model also works very well. However, for some reason, it is evaluating to exactly the same results as our LSTM model, which seems suspicious. The confusion matrices are exactly identical.

### BERT Model

In [31]:
import tensorflow as tf
import huggingface_hub
from transformers import AutoTokenizer, TFBertModel, AutoModelForCausalLM

In [32]:
model_name = "bert-base-uncased"
model = TFBertModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [33]:
# Analyze the token count across the articles after tokenizing all text for some extra data exploration
left_token_count = sum(len(tokenizer.tokenize(str(text))) for text in left_df["text"] if pd.notna(text))
right_token_count = sum(len(tokenizer.tokenize(str(text))) for text in right_df["text"] if pd.notna(text))
center_token_count = sum(len(tokenizer.tokenize(str(text))) for text in center_df["text"] if pd.notna(text))

print("Left-leaning articles token count:", left_token_count)
print("Right-leaning articles token count:", right_token_count)
print("Center-leaning articles token count:", center_token_count)

Left-leaning articles token count: 837527
Right-leaning articles token count: 620797
Center-leaning articles token count: 388367


We will use the process described by Keras to train on a portion of our data: https://keras.io/keras_hub/api/models/bert/bert_text_classifier/

In [34]:
import keras_hub
import tensorflow as tf
from tensorflow import keras
import numpy as np

features = X_train.copy()
labels = y_train.copy()
# Pretrained classifier.
classifier = keras_hub.models.BertTextClassifier.from_preset(
    "bert_base_en_uncased",
    num_classes=3,
)
classifier.fit(x=features, y=labels, batch_size=2)
classifier.predict(x=features, batch_size=2)

# Re-compile (e.g., with a new learning rate).
classifier.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True), # SparseCategoricalCrossentropy
    optimizer="adam",
    jit_compile=True,
)
# Access backbone programmatically (e.g., to change `trainable`).
classifier.backbone.trainable = False
# Fit again.
classifier.fit(x=features, y=labels, batch_size=2)


100%|██████████| 510/510 [00:00<00:00, 1.35MB/s]


100%|██████████| 418M/418M [00:02<00:00, 171MB/s]


100%|██████████| 547/547 [00:00<00:00, 837kB/s]


7614/7614 ━━━━━━━━━━━━━━━━━━━━ 1838s 232ms/step - loss: 1.0396 - sparse_categorical_accuracy: 0.4752
7614/7614 ━━━━━━━━━━━━━━━━━━━━ 472s 62ms/step
7614/7614 ━━━━━━━━━━━━━━━━━━━━ 611s 75ms/step - loss: 1.1985 - sparse_categorical_accuracy: 0.4195


BERT Baseline Model Evaluation

In [35]:
# Create a tf.data.Dataset for evaluation
eval_dataset = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(2)

# Evaluate the model
loss, accuracy = classifier.evaluate(eval_dataset) # Use classifier instead of model
print(f"Loss: {loss}, Accuracy: {accuracy}")

from sklearn.metrics import classification_report

# Get predictions
preds = classifier.predict(eval_dataset) # Use classifier instead of model
y_pred = np.argmax(preds, axis=1)  # Get predicted labels

# Get true labels
y_true = np.concatenate([y for x, y in eval_dataset], axis=0)

print(classification_report(y_true, y_pred, target_names=['left', 'center', 'right']))

1632/1632 ━━━━━━━━━━━━━━━━━━━━ 107s 63ms/step - loss: 1.3397 - sparse_categorical_accuracy: 0.4536
Loss: 1.3039817810058594, Accuracy: 0.4722647964954376
1632/1632 ━━━━━━━━━━━━━━━━━━━━ 107s 63ms/step
              precision    recall  f1-score   support

        left       0.47      1.00      0.64      1541
      center       0.00      0.00      0.00       638
       right       0.00      0.00      0.00      1084

    accuracy                           0.47      3263
   macro avg       0.16      0.33      0.21      3263
weighted avg       0.22      0.47      0.30      3263



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [38]:
print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")


Accuracy: 0.4723


### Create requirements.txt

In [36]:
!pip freeze > requirements.txt